name: healthesy
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  intl: any
  go_router: ^14.3.0
  logging: ^1.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.0
#  charts_flutter: ^0.12.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  flutter_html_2: ^0.1.0
  path_provider: ^2.0.6
  http: ^1.2.2
  video_player: ^2.7.0
  image_picker: ^1.1.2
  pedometer: ^4.0.2
  
  cupertino_icons: ^1.0.8
  community_charts_flutter: ^1.0.4
  flutter_launcher_icons: ^0.14.1

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # for intl and localization
  generate: true
  
  uses-material-design: true
  assets:
    - assets/images/

